// <auto-generated />
namespace Fundraising_Capstone2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class phoneCallee : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(phoneCallee));
        
        string IMigrationMetadata.Id
        {
            get { return "201912060014126_phoneCallee"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
